CREATE TABLE ACCOUNT
(
	ID			INT NOT NULL , 
	LOGIN		VARCHAR(255) NOT NULL,
	PASSWORD	VARCHAR(255) NOT NULL,
	FIRST_NAME		VARCHAR(240) NOT NULL,
	LAST_NAME		VARCHAR(240) NOT NULL,
	SECOND_NAME		VARCHAR(240) NOT NULL,

	CONSTRAINT XPKACCOUNT PRIMARY KEY (ID)

)

CREATE TABLE [ROLE] 
(
   ID         INT NOT NULL,
   NAME       VARCHAR (240) NOT NULL,

   CONSTRAINT XPKROLE PRIMARY KEY (ID)
)

CREATE TABLE ACCOUNT_ROLE
(

   ID              INT NOT NULL,
   ACCOUNT_ID      INT NOT NULL,
   ROLE_ID         INT NOT NULL,
      
   CONSTRAINT XPKACCOUNT_ROLE PRIMARY KEY (ID),
   CONSTRAINT XAK1ACCOUNT_ROLE UNIQUE (ACCOUNT_ID, ROLE_ID)
   
);



CREATE TABLE RESULT
(
	ID			INT NOT NULL, 
	ACCOUNT_ID	INT NOT NULL,
	TEST_ID		INT NOT NULL,
	RESULT		VARCHAR(100) DEFAULT '0',

	CONSTRAINT XPKRESULT PRIMARY KEY (ID)

)



CREATE TABLE STUDENT
(
	ID			INT NOT NULL, 
	ACCOUNT_ID	INT NOT NULL,
	STUDENT_GROUP_ID	INT NOT NULL,
	
	CONSTRAINT XPKSTUDENT PRIMARY KEY (ID) 

)


CREATE TABLE TEST
(
	ID		INT NOT NULL, 
	NAME	VARCHAR(255) NOT NULL,
	THEME	VARCHAR(100) NOT NULL,

	CONSTRAINT XPKTEST PRIMARY KEY (ID) 
)

CREATE TABLE QUESTION
(
	ID		INT NOT NULL, 
	TITLE	VARCHAR(255) NOT NULL,
	CONTENT TEXT NOT NULL,
	TEST_ID INT NOT NULL,

	CONSTRAINT XPKQUESTION PRIMARY KEY (ID) 
)


CREATE TABLE ANSWER
(
	ID			INT NOT NULL, 
	QUESTION_ID	INT NOT NULL,
	CONTENT		TEXT NOT NULL,
	IS_RIGHT	TINYINT NOT NULL DEFAULT 0,

	CONSTRAINT XPKANSWER PRIMARY KEY (ID) 
)


CREATE TABLE STUDENT_GROUP
(
	ID		INT NOT NULL, 
	NAME	VARCHAR(255) NOT NULL,


	CONSTRAINT XPKSTUDENT_GROUP PRIMARY KEY (ID) 
)


ALTER TABLE ACCOUNT_ROLE
	ADD CONSTRAINT R1ACCOUNT_ROLE FOREIGN KEY (ACCOUNT_ID) 
		REFERENCES ACCOUNT(ID)

ALTER TABLE ACCOUNT_ROLE
	ADD CONSTRAINT R2ACCOUNT_ROLE FOREIGN KEY (ROLE_ID) 
		REFERENCES [ROLE](ID)


		
ALTER TABLE RESULT
	ADD CONSTRAINT R1RESULT FOREIGN KEY (ACCOUNT_ID) 
		REFERENCES ACCOUNT(ID)

ALTER TABLE RESULT
	ADD CONSTRAINT R2RESULT FOREIGN KEY (TEST_ID) 
		REFERENCES TEST(ID)

		
ALTER TABLE STUDENT
	ADD CONSTRAINT R1STUDENT FOREIGN KEY (ACCOUNT_ID) 
		REFERENCES ACCOUNT(ID)

ALTER TABLE STUDENT
	ADD CONSTRAINT R2STUDENT FOREIGN KEY (STUDENT_GROUP_ID) 
		REFERENCES STUDENT_GROUP(ID)

		
ALTER TABLE QUESTION
	ADD CONSTRAINT R1QUESTION FOREIGN KEY (TEST_ID) 
		REFERENCES TEST(ID)

		
ALTER TABLE ANSWER
	ADD CONSTRAINT R1ANSWER FOREIGN KEY (QUESTION_ID) 
		REFERENCES QUESTION(ID)


