//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.ACCOUNT_ROLE = new HashSet<AccountRole>();
            this.RESULT = new HashSet<Result>();
            this.STUDENT = new HashSet<Student>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SecondName { get; set; }
    
        public virtual ICollection<AccountRole> ACCOUNT_ROLE { get; set; }
        public virtual ICollection<Result> RESULT { get; set; }
        public virtual ICollection<Student> STUDENT { get; set; }
    }
}
