//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("MainModel", "R1QUESTION", "TEST", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Server.DB.TEST), "QUESTION", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Server.DB.QUESTION))]

// Original file name:
// Generation date: 5/21/2014 12:38:56 PM
namespace Server.DB
{
    
    /// <summary>
    /// There are no comments for MainEntitie in the schema.
    /// </summary>
    public partial class MainEntitie : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new MainEntitie object using the connection string found in the 'MainEntitie' section of the application configuration file.
        /// </summary>
        public MainEntitie() : 
                base("name=MainEntitie", "MainEntitie")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MainEntitie object.
        /// </summary>
        public MainEntitie(string connectionString) : 
                base(connectionString, "MainEntitie")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new MainEntitie object.
        /// </summary>
        public MainEntitie(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "MainEntitie")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for ACCOUNT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ACCOUNT> ACCOUNT
        {
            get
            {
                if ((this._ACCOUNT == null))
                {
                    this._ACCOUNT = base.CreateQuery<ACCOUNT>("[ACCOUNT]");
                }
                return this._ACCOUNT;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ACCOUNT> _ACCOUNT;
        /// <summary>
        /// There are no comments for ACCOUNT_ROLE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ACCOUNT_ROLE> ACCOUNT_ROLE
        {
            get
            {
                if ((this._ACCOUNT_ROLE == null))
                {
                    this._ACCOUNT_ROLE = base.CreateQuery<ACCOUNT_ROLE>("[ACCOUNT_ROLE]");
                }
                return this._ACCOUNT_ROLE;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ACCOUNT_ROLE> _ACCOUNT_ROLE;
        /// <summary>
        /// There are no comments for ANSWER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ANSWER> ANSWER
        {
            get
            {
                if ((this._ANSWER == null))
                {
                    this._ANSWER = base.CreateQuery<ANSWER>("[ANSWER]");
                }
                return this._ANSWER;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ANSWER> _ANSWER;
        /// <summary>
        /// There are no comments for QUESTION in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<QUESTION> QUESTION
        {
            get
            {
                if ((this._QUESTION == null))
                {
                    this._QUESTION = base.CreateQuery<QUESTION>("[QUESTION]");
                }
                return this._QUESTION;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<QUESTION> _QUESTION;
        /// <summary>
        /// There are no comments for RESULT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<RESULT> RESULT
        {
            get
            {
                if ((this._RESULT == null))
                {
                    this._RESULT = base.CreateQuery<RESULT>("[RESULT]");
                }
                return this._RESULT;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<RESULT> _RESULT;
        /// <summary>
        /// There are no comments for ROLE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ROLE> ROLE
        {
            get
            {
                if ((this._ROLE == null))
                {
                    this._ROLE = base.CreateQuery<ROLE>("[ROLE]");
                }
                return this._ROLE;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ROLE> _ROLE;
        /// <summary>
        /// There are no comments for STUDENT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<STUDENT> STUDENT
        {
            get
            {
                if ((this._STUDENT == null))
                {
                    this._STUDENT = base.CreateQuery<STUDENT>("[STUDENT]");
                }
                return this._STUDENT;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<STUDENT> _STUDENT;
        /// <summary>
        /// There are no comments for STUDENT_GROUP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<STUDENT_GROUP> STUDENT_GROUP
        {
            get
            {
                if ((this._STUDENT_GROUP == null))
                {
                    this._STUDENT_GROUP = base.CreateQuery<STUDENT_GROUP>("[STUDENT_GROUP]");
                }
                return this._STUDENT_GROUP;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<STUDENT_GROUP> _STUDENT_GROUP;
        /// <summary>
        /// There are no comments for TEST in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<TEST> TEST
        {
            get
            {
                if ((this._TEST == null))
                {
                    this._TEST = base.CreateQuery<TEST>("[TEST]");
                }
                return this._TEST;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<TEST> _TEST;
        /// <summary>
        /// There are no comments for ACCOUNT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToACCOUNT(ACCOUNT aCCOUNT)
        {
            base.AddObject("ACCOUNT", aCCOUNT);
        }
        /// <summary>
        /// There are no comments for ACCOUNT_ROLE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToACCOUNT_ROLE(ACCOUNT_ROLE aCCOUNT_ROLE)
        {
            base.AddObject("ACCOUNT_ROLE", aCCOUNT_ROLE);
        }
        /// <summary>
        /// There are no comments for ANSWER in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToANSWER(ANSWER aNSWER)
        {
            base.AddObject("ANSWER", aNSWER);
        }
        /// <summary>
        /// There are no comments for QUESTION in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToQUESTION(QUESTION qUESTION)
        {
            base.AddObject("QUESTION", qUESTION);
        }
        /// <summary>
        /// There are no comments for RESULT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToRESULT(RESULT rESULT)
        {
            base.AddObject("RESULT", rESULT);
        }
        /// <summary>
        /// There are no comments for ROLE in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToROLE(ROLE rOLE)
        {
            base.AddObject("ROLE", rOLE);
        }
        /// <summary>
        /// There are no comments for STUDENT in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSTUDENT(STUDENT sTUDENT)
        {
            base.AddObject("STUDENT", sTUDENT);
        }
        /// <summary>
        /// There are no comments for STUDENT_GROUP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSTUDENT_GROUP(STUDENT_GROUP sTUDENT_GROUP)
        {
            base.AddObject("STUDENT_GROUP", sTUDENT_GROUP);
        }
        /// <summary>
        /// There are no comments for TEST in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToTEST(TEST tEST)
        {
            base.AddObject("TEST", tEST);
        }
    }
    /// <summary>
    /// There are no comments for MainModel.ACCOUNT in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MainModel", Name="ACCOUNT")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ACCOUNT : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ACCOUNT object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="lOGIN">Initial value of LOGIN.</param>
        /// <param name="pASSWORD">Initial value of PASSWORD.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ACCOUNT CreateACCOUNT(int id, string lOGIN, string pASSWORD)
        {
            ACCOUNT aCCOUNT = new ACCOUNT();
            aCCOUNT.ID = id;
            aCCOUNT.LOGIN = lOGIN;
            aCCOUNT.PASSWORD = pASSWORD;
            return aCCOUNT;
        }
        /// <summary>
        /// There are no comments for property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for property LOGIN in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string LOGIN
        {
            get
            {
                return this._LOGIN;
            }
            set
            {
                this.OnLOGINChanging(value);
                this.ReportPropertyChanging("LOGIN");
                this._LOGIN = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("LOGIN");
                this.OnLOGINChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _LOGIN;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLOGINChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnLOGINChanged();
        /// <summary>
        /// There are no comments for property PASSWORD in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string PASSWORD
        {
            get
            {
                return this._PASSWORD;
            }
            set
            {
                this.OnPASSWORDChanging(value);
                this.ReportPropertyChanging("PASSWORD");
                this._PASSWORD = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("PASSWORD");
                this.OnPASSWORDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _PASSWORD;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPASSWORDChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnPASSWORDChanged();
    }
    /// <summary>
    /// There are no comments for MainModel.ACCOUNT_ROLE in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ACCOUNT_ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MainModel", Name="ACCOUNT_ROLE")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ACCOUNT_ROLE : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ACCOUNT_ROLE object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="aCCOUNT_ID">Initial value of ACCOUNT_ID.</param>
        /// <param name="rOLE_ID">Initial value of ROLE_ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ACCOUNT_ROLE CreateACCOUNT_ROLE(int id, int aCCOUNT_ID, int rOLE_ID)
        {
            ACCOUNT_ROLE aCCOUNT_ROLE = new ACCOUNT_ROLE();
            aCCOUNT_ROLE.ID = id;
            aCCOUNT_ROLE.ACCOUNT_ID = aCCOUNT_ID;
            aCCOUNT_ROLE.ROLE_ID = rOLE_ID;
            return aCCOUNT_ROLE;
        }
        /// <summary>
        /// There are no comments for property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for property ACCOUNT_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ACCOUNT_ID
        {
            get
            {
                return this._ACCOUNT_ID;
            }
            set
            {
                this.OnACCOUNT_IDChanging(value);
                this.ReportPropertyChanging("ACCOUNT_ID");
                this._ACCOUNT_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ACCOUNT_ID");
                this.OnACCOUNT_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ACCOUNT_ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnACCOUNT_IDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnACCOUNT_IDChanged();
        /// <summary>
        /// There are no comments for property ROLE_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ROLE_ID
        {
            get
            {
                return this._ROLE_ID;
            }
            set
            {
                this.OnROLE_IDChanging(value);
                this.ReportPropertyChanging("ROLE_ID");
                this._ROLE_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ROLE_ID");
                this.OnROLE_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ROLE_ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnROLE_IDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnROLE_IDChanged();
    }
    /// <summary>
    /// There are no comments for MainModel.ANSWER in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MainModel", Name="ANSWER")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ANSWER : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ANSWER object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="qUESTION_ID">Initial value of QUESTION_ID.</param>
        /// <param name="cONTENT">Initial value of CONTENT.</param>
        /// <param name="iS_RIGHT">Initial value of IS_RIGHT.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ANSWER CreateANSWER(int id, int qUESTION_ID, string cONTENT, byte iS_RIGHT)
        {
            ANSWER aNSWER = new ANSWER();
            aNSWER.ID = id;
            aNSWER.QUESTION_ID = qUESTION_ID;
            aNSWER.CONTENT = cONTENT;
            aNSWER.IS_RIGHT = iS_RIGHT;
            return aNSWER;
        }
        /// <summary>
        /// There are no comments for property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for property QUESTION_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int QUESTION_ID
        {
            get
            {
                return this._QUESTION_ID;
            }
            set
            {
                this.OnQUESTION_IDChanging(value);
                this.ReportPropertyChanging("QUESTION_ID");
                this._QUESTION_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("QUESTION_ID");
                this.OnQUESTION_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _QUESTION_ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnQUESTION_IDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnQUESTION_IDChanged();
        /// <summary>
        /// There are no comments for property CONTENT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string CONTENT
        {
            get
            {
                return this._CONTENT;
            }
            set
            {
                this.OnCONTENTChanging(value);
                this.ReportPropertyChanging("CONTENT");
                this._CONTENT = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CONTENT");
                this.OnCONTENTChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _CONTENT;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCONTENTChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCONTENTChanged();
        /// <summary>
        /// There are no comments for property IS_RIGHT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public byte IS_RIGHT
        {
            get
            {
                return this._IS_RIGHT;
            }
            set
            {
                this.OnIS_RIGHTChanging(value);
                this.ReportPropertyChanging("IS_RIGHT");
                this._IS_RIGHT = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("IS_RIGHT");
                this.OnIS_RIGHTChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private byte _IS_RIGHT;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIS_RIGHTChanging(byte value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIS_RIGHTChanged();
    }
    /// <summary>
    /// There are no comments for MainModel.QUESTION in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MainModel", Name="QUESTION")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class QUESTION : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new QUESTION object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="tITLE">Initial value of TITLE.</param>
        /// <param name="cONTENT">Initial value of CONTENT.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static QUESTION CreateQUESTION(int id, string tITLE, string cONTENT)
        {
            QUESTION qUESTION = new QUESTION();
            qUESTION.ID = id;
            qUESTION.TITLE = tITLE;
            qUESTION.CONTENT = cONTENT;
            return qUESTION;
        }
        /// <summary>
        /// There are no comments for property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for property TITLE in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string TITLE
        {
            get
            {
                return this._TITLE;
            }
            set
            {
                this.OnTITLEChanging(value);
                this.ReportPropertyChanging("TITLE");
                this._TITLE = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("TITLE");
                this.OnTITLEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _TITLE;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTITLEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTITLEChanged();
        /// <summary>
        /// There are no comments for property CONTENT in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string CONTENT
        {
            get
            {
                return this._CONTENT;
            }
            set
            {
                this.OnCONTENTChanging(value);
                this.ReportPropertyChanging("CONTENT");
                this._CONTENT = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("CONTENT");
                this.OnCONTENTChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _CONTENT;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCONTENTChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCONTENTChanged();
        /// <summary>
        /// There are no comments for TEST in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MainModel", "R1QUESTION", "TEST")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public TEST TEST
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TEST>("MainModel.R1QUESTION", "TEST").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TEST>("MainModel.R1QUESTION", "TEST").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for TEST in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<TEST> TESTReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<TEST>("MainModel.R1QUESTION", "TEST");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<TEST>("MainModel.R1QUESTION", "TEST", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for MainModel.RESULT in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MainModel", Name="RESULT")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class RESULT : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new RESULT object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="aCCOUNT_ID">Initial value of ACCOUNT_ID.</param>
        /// <param name="tEST_ID">Initial value of TEST_ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static RESULT CreateRESULT(int id, int aCCOUNT_ID, int tEST_ID)
        {
            RESULT rESULT = new RESULT();
            rESULT.ID = id;
            rESULT.ACCOUNT_ID = aCCOUNT_ID;
            rESULT.TEST_ID = tEST_ID;
            return rESULT;
        }
        /// <summary>
        /// There are no comments for property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for property ACCOUNT_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ACCOUNT_ID
        {
            get
            {
                return this._ACCOUNT_ID;
            }
            set
            {
                this.OnACCOUNT_IDChanging(value);
                this.ReportPropertyChanging("ACCOUNT_ID");
                this._ACCOUNT_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ACCOUNT_ID");
                this.OnACCOUNT_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ACCOUNT_ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnACCOUNT_IDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnACCOUNT_IDChanged();
        /// <summary>
        /// There are no comments for property TEST_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int TEST_ID
        {
            get
            {
                return this._TEST_ID;
            }
            set
            {
                this.OnTEST_IDChanging(value);
                this.ReportPropertyChanging("TEST_ID");
                this._TEST_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("TEST_ID");
                this.OnTEST_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _TEST_ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTEST_IDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTEST_IDChanged();
        /// <summary>
        /// There are no comments for property RESULT1 in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string RESULT1
        {
            get
            {
                return this._RESULT1;
            }
            set
            {
                this.OnRESULT1Changing(value);
                this.ReportPropertyChanging("RESULT1");
                this._RESULT1 = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("RESULT1");
                this.OnRESULT1Changed();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _RESULT1;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRESULT1Changing(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnRESULT1Changed();
    }
    /// <summary>
    /// There are no comments for MainModel.ROLE in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MainModel", Name="ROLE")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ROLE : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ROLE object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="nAME">Initial value of NAME.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ROLE CreateROLE(int id, string nAME)
        {
            ROLE rOLE = new ROLE();
            rOLE.ID = id;
            rOLE.NAME = nAME;
            return rOLE;
        }
        /// <summary>
        /// There are no comments for property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for property NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NAME
        {
            get
            {
                return this._NAME;
            }
            set
            {
                this.OnNAMEChanging(value);
                this.ReportPropertyChanging("NAME");
                this._NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NAME");
                this.OnNAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NAME;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNAMEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNAMEChanged();
    }
    /// <summary>
    /// There are no comments for MainModel.STUDENT in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MainModel", Name="STUDENT")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class STUDENT : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new STUDENT object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="aCCOUNT_ID">Initial value of ACCOUNT_ID.</param>
        /// <param name="gROUP_ID">Initial value of GROUP_ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static STUDENT CreateSTUDENT(int id, int aCCOUNT_ID, int gROUP_ID)
        {
            STUDENT sTUDENT = new STUDENT();
            sTUDENT.ID = id;
            sTUDENT.ACCOUNT_ID = aCCOUNT_ID;
            sTUDENT.GROUP_ID = gROUP_ID;
            return sTUDENT;
        }
        /// <summary>
        /// There are no comments for property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for property ACCOUNT_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ACCOUNT_ID
        {
            get
            {
                return this._ACCOUNT_ID;
            }
            set
            {
                this.OnACCOUNT_IDChanging(value);
                this.ReportPropertyChanging("ACCOUNT_ID");
                this._ACCOUNT_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ACCOUNT_ID");
                this.OnACCOUNT_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ACCOUNT_ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnACCOUNT_IDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnACCOUNT_IDChanged();
        /// <summary>
        /// There are no comments for property GROUP_ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int GROUP_ID
        {
            get
            {
                return this._GROUP_ID;
            }
            set
            {
                this.OnGROUP_IDChanging(value);
                this.ReportPropertyChanging("GROUP_ID");
                this._GROUP_ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("GROUP_ID");
                this.OnGROUP_IDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _GROUP_ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGROUP_IDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnGROUP_IDChanged();
    }
    /// <summary>
    /// There are no comments for MainModel.STUDENT_GROUP in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MainModel", Name="STUDENT_GROUP")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class STUDENT_GROUP : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new STUDENT_GROUP object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="nAME">Initial value of NAME.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static STUDENT_GROUP CreateSTUDENT_GROUP(int id, string nAME)
        {
            STUDENT_GROUP sTUDENT_GROUP = new STUDENT_GROUP();
            sTUDENT_GROUP.ID = id;
            sTUDENT_GROUP.NAME = nAME;
            return sTUDENT_GROUP;
        }
        /// <summary>
        /// There are no comments for property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for property NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NAME
        {
            get
            {
                return this._NAME;
            }
            set
            {
                this.OnNAMEChanging(value);
                this.ReportPropertyChanging("NAME");
                this._NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NAME");
                this.OnNAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NAME;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNAMEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNAMEChanged();
    }
    /// <summary>
    /// There are no comments for MainModel.TEST in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="MainModel", Name="TEST")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class TEST : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new TEST object.
        /// </summary>
        /// <param name="id">Initial value of ID.</param>
        /// <param name="nAME">Initial value of NAME.</param>
        /// <param name="tHEME">Initial value of THEME.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static TEST CreateTEST(int id, string nAME, string tHEME)
        {
            TEST tEST = new TEST();
            tEST.ID = id;
            tEST.NAME = nAME;
            tEST.THEME = tHEME;
            return tEST;
        }
        /// <summary>
        /// There are no comments for property ID in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this.ReportPropertyChanging("ID");
                this._ID = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("ID");
                this.OnIDChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _ID;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for property NAME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string NAME
        {
            get
            {
                return this._NAME;
            }
            set
            {
                this.OnNAMEChanging(value);
                this.ReportPropertyChanging("NAME");
                this._NAME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("NAME");
                this.OnNAMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _NAME;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNAMEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNAMEChanged();
        /// <summary>
        /// There are no comments for property THEME in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string THEME
        {
            get
            {
                return this._THEME;
            }
            set
            {
                this.OnTHEMEChanging(value);
                this.ReportPropertyChanging("THEME");
                this._THEME = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("THEME");
                this.OnTHEMEChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _THEME;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTHEMEChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTHEMEChanged();
        /// <summary>
        /// There are no comments for QUESTION in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MainModel", "R1QUESTION", "QUESTION")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<QUESTION> QUESTION
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<QUESTION>("MainModel.R1QUESTION", "QUESTION");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<QUESTION>("MainModel.R1QUESTION", "QUESTION", value);
                }
            }
        }
    }
}
