//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int Id { get; set; }
        public int AccountId { get; set; }
        public int StudentGroupId { get; set; }
    
        public virtual Account ACCOUNT { get; set; }
        public virtual StudentGroup STUDENT_GROUP { get; set; }
    }
}
