//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Server.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.QUESTION = new HashSet<Question>();
            this.RESULT = new HashSet<Result>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Them { get; set; }
    
        public virtual ICollection<Question> QUESTION { get; set; }
        public virtual ICollection<Result> RESULT { get; set; }
    }
}
